# .github/workflows/update_ai_labor_index.yml
name: Update AI Labor Market Index

on:
  schedule:
    # Run weekly on Sunday at 2 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch:  # Allow manual triggering

jobs:
  update_index:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pandas numpy nltk

      - name: Download NLTK data
        run: |
          python -c "import nltk; nltk.download('punkt'); nltk.download('stopwords')"
      
      - name: Create directories
        run: |
          mkdir -p data/raw/arxiv
          mkdir -p data/raw/bls
          mkdir -p data/raw/jobs
          mkdir -p data/raw/news
          mkdir -p data/processed
      
      - name: Collect ArXiv data
        run: python scripts/collection/collect_arxiv.py
      
      - name: Collect BLS data
        run: python scripts/collection/collect_bls.py
        env:
          BLS_API_KEY: ${{ secrets.BLS_API_KEY }}
      
      - name: Collect job data
        run: python scripts/collection/collect_jobs.py

      - name: Collect news data
        run: python scripts/collection/collect_news.py
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
      
      - name: Process data
        run: |
          python scripts/processing/process_research.py
          python scripts/processing/process_employment.py
          python scripts/processing/process_jobs.py
          python scripts/processing/process_news.py
      
      - name: Calculate index
        run: python scripts/analysis/calculate_index.py
      
      - name: Update files in repository
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add data/processed/
          git commit -m "Update AI Labor Market Index $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
